### ISSUE TITLE
chrome does not add cookies on set-cookie response

### ISSUE THREAD

**Issue by antonkulaga** [denigma/akka-http-extensions#1]
Chrome does not add cookies on set-cookied response. Have not clue why it is happening=(

**Comment by antonkulaga** [comment]
@rmihael ,если будет немного времени, можешь глянуть, пожалуйста, а то уже замучался с браузерной частью кукисов. Я эксперементировал, везде ставятся за исключением логина,в логине-регистрации - передаются в респонсе но в dom.document.cookie не записываются =(

**Comment by rmihael** [comment]
Сегодня в обед попробую разобраться

**Comment by antonkulaga** [comment]
Fixed
